### ISSUE TITLE
An error occurred with the basic command.

### ISSUE THREAD

**Issue by Dosin-Lee** [mhallerud/multiplex_wormhole#1]
I simply want to check if this works.
Primer3 and mfe are already installed, and I've modified line 18 of scripts/primer3.sh to fit my environment.
Below is the command I used. What could be the problem?

----------------------------------------------------------------------------------------------------

My comand:
./multiplex_primer_design.sh ./examples/Input_Templates.csv output test
----------------------------------------------------------------------------------------------------
Running optimization process.......
......Run 1

......Run 2

......Run 3
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

......Run 4
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

......Run 5
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

......Run 6
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

......Run 7
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

......Run 8

......Run 9

......Run 10
Traceback (most recent call last):
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 472, in <module>
    main()
  File "/home/nanopore/data/multiplex_wormhole/./scripts/optimize_primers.py", line 163, in main
    AddWorstToAllowed(curr_worst, allowed_pairs_rmv, primer_loci, primer_IDs)
                      ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'curr_worst' where it is not associated with a value

**Comment by mhallerud** [comment]
Hi @Dosin-Lee. I have not seen this error before, so without digging into it I am not exactly sure why the script is breaking. It is providing results for some of your runs (runs 1, 2, 8, 9 were successful). It seems successfully installed, the problem looks to be a bug in my code. This script is still very much in development, so it is possible that I need to check that I uploaded the correct version. So far, myself and my labmate have been using the script on two separate machines and datasets, but the pipeline has not been validated on any other datasets or machines.
